#logitech gamepad F310
#teleop config
/**:
  ros__parameters:
    axis_linear:  # Forward/Back
      x: 3  # right stick left
      y: 4  # right stick up
    axis_angular:  # Left/Right
      yaw: 0 # left stick left

    scale_linear:
      x: 0.001
      y: 0.001
    scale_angular:
      yaw: 0.01

    scale_linear_turbo:
      x: 0.001
      y: 0.001
    scale_angular_turbo:
      yaw: 0.01


    enable_button: 5  # right shoulder
    enable_turbo_button: 4  # left shoulder

#joy config
/**:
  ros__parameters:
    device_name: 'Logitech Gamepad F310'
    deadzone: 0.0
    autorepeat_rate: 20.0
    coalesce_interval_ms: 50
